[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_lend_borrow = "GLXLYqFJR6kLHUAegVWEDz7dUMngL4kRajF1iNi7duvg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
